name: API Tests with Allure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Run tests inside Docker Compose (make sure your tests run and write results to ./allure-results)
      - name: Run Docker Compose Tests
        run: docker compose up --build --abort-on-container-exit

      # Upload allure-results folder as artifact (optional, useful for debugging or separate download)
      - name: Upload Allure results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: ./allure-results
          retention-days: 30

      # Install Allure CLI to generate the HTML report
      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -zxvf allure-2.27.0.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      # Generate the HTML report from results
      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report

      # Deploy generated report to GitHub Pages (only on main branch)
      - name: Deploy Allure Report to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Update Allure report [skip ci]'
